# This rule is not used by the project radiusguardcontroller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to networking.hsuan.app resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: radiusguardcontroller
    app.kubernetes.io/managed-by: kustomize
  name: radiusguard-viewer-role
rules:
- apiGroups:
  - networking.hsuan.app
  resources:
  - radiusguards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.hsuan.app
  resources:
  - radiusguards/status
  verbs:
  - get
