---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.hsuan.app
  resources:
  - radiusguards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.hsuan.app
  resources:
  - radiusguards/finalizers
  verbs:
  - update
- apiGroups:
  - networking.hsuan.app
  resources:
  - radiusguards/status
  verbs:
  - get
  - patch
  - update
